//IMPORTANDO OS DADOS DO ARQUIVO ESTUDNATE.JSON (UTILIZANDO O REQUIRE), E PASSANDO ELE PARA A VARIÁVEL ESTUDANTE
//AO PASSAR OS DADOS PARA A CONSTANTE ESTUDANTE ESTAMOS CONVERTANDO O JSON PARA UM OBJETO JAVASCRIPT, ASSIM PODEMOS MANIPULAR OS DADOS COM MÉTODOS DE OBJETOS

const estudante = require('./estudante.json')
console.log(estudante)
console.log(typeof estudante) //SAIDA: OBJECT


const keys = Object.keys(estudante) 
console.log(keys)